import { FEATURED_COUNTRIES } from "./countries-geo";

export const CATEGORIES = [
  {
    slug: "retratos",
    name: "Retratos",
    description: "Miradas, gestos y la humanidad detrás de cada rostro.",
    sortOrder: 0,
  },
  {
    slug: "paisaje",
    name: "Paisaje",
    description: "Horizontes, luz natural y la escala del mundo.",
    sortOrder: 1,
  },
  {
    slug: "urbano",
    name: "Urbano",
    description: "El pulso de la calle y la vida entre edificios.",
    sortOrder: 2,
  },
  {
    slug: "arquitectura",
    name: "Arquitectura",
    description: "Líneas, geometría y estructuras que cuentan historias.",
    sortOrder: 3,
  },
  {
    slug: "naturaleza",
    name: "Naturaleza",
    description: "Fauna y flora en su estado más puro.",
    sortOrder: 4,
  },
  {
    slug: "blanco-y-negro",
    name: "Blanco y Negro",
    description: "Contraste, textura y emoción sin color.",
    sortOrder: 5,
  },
] as const;

type CategorySlug = (typeof CATEGORIES)[number]["slug"];
type CountrySlug = (typeof FEATURED_COUNTRIES)[number]["slug"];

export interface SeedPhoto {
  slug: string;
  title: string;
  description: string;
  location: string;
  capturedAt: string;
  category: CategorySlug;
  country: CountrySlug;
  width: number;
  height: number;
  featured: boolean;
  prices: {
    type: "DIGITAL" | "PRINT";
    label: string;
    description: string;
    amountCents: number;
  }[];
}

const DIGITAL_PRICE = {
  type: "DIGITAL" as const,
  label: "Descarga digital",
  description: "Archivo JPEG de alta resolución, licencia de uso personal.",
  amountCents: 1500,
};

const PRINT_PRICES = [
  {
    type: "PRINT" as const,
    label: 'Impresión 30x40 cm',
    description: "Papel fine art mate, edición numerada.",
    amountCents: 5900,
  },
  {
    type: "PRINT" as const,
    label: 'Impresión 50x70 cm',
    description: "Papel fine art mate, edición numerada.",
    amountCents: 9900,
  },
  {
    type: "PRINT" as const,
    label: 'Impresión 70x100 cm enmarcada',
    description: "Marco de madera natural, listo para colgar.",
    amountCents: 18900,
  },
];

export const PHOTOS: SeedPhoto[] = [
  {
    slug: "luz-de-mediodia-marrakech",
    title: "Luz de mediodía, Marrakech",
    description:
      "El sol cenital atraviesa los callejones del zoco y dibuja sombras nítidas sobre el color ocre de los muros.",
    location: "Marrakech",
    capturedAt: "2022-04-12",
    category: "urbano",
    country: "marruecos",
    width: 4,
    height: 5,
    featured: true,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "retrato-tejedora-fez",
    title: "Tejedora, Fez",
    description:
      "Un retrato hecho con luz de ventana en un taller textil del casco antiguo.",
    location: "Fez",
    capturedAt: "2022-04-15",
    category: "retratos",
    country: "marruecos",
    width: 4,
    height: 5,
    featured: true,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "glaciar-al-amanecer",
    title: "Glaciar al amanecer",
    description:
      "Jökulsárlón antes de que lleguen los primeros visitantes, cuando el hielo aún es azul profundo.",
    location: "Jökulsárlón",
    capturedAt: "2021-09-02",
    category: "paisaje",
    country: "islandia",
    width: 3,
    height: 2,
    featured: true,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "aurora-sobre-vik",
    title: "Aurora sobre Vík",
    description:
      "Una noche despejada de septiembre sobre la playa de arena negra de Vík í Mýrdal.",
    location: "Vík í Mýrdal",
    capturedAt: "2021-09-05",
    category: "paisaje",
    country: "islandia",
    width: 3,
    height: 2,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "fiordo-en-silencio",
    title: "Fiordo en silencio",
    description:
      "La niebla se levanta lentamente sobre el Geirangerfjord al final del verano ártico.",
    location: "Geirangerfjord",
    capturedAt: "2022-08-20",
    category: "paisaje",
    country: "noruega",
    width: 4,
    height: 3,
    featured: true,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "cabana-roja-nieve",
    title: "Cabaña roja en la nieve",
    description: "Arquitectura tradicional noruega frente al blanco absoluto del invierno.",
    location: "Lofoten",
    capturedAt: "2022-02-14",
    category: "arquitectura",
    country: "noruega",
    width: 4,
    height: 5,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "torres-eiffel-lluvia",
    title: "Torre Eiffel bajo la lluvia",
    description: "Una tarde gris de octubre desde el Trocadéro, con el hierro reflejando la luz plana.",
    location: "París",
    capturedAt: "2018-10-11",
    category: "arquitectura",
    country: "francia",
    width: 3,
    height: 4,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "vinedos-provenza",
    title: "Viñedos de la Provenza",
    description: "Hileras infinitas bajo un cielo de verano en Luberon.",
    location: "Luberon",
    capturedAt: "2018-07-03",
    category: "paisaje",
    country: "francia",
    width: 3,
    height: 2,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "cafe-parisino-bn",
    title: "Café parisino",
    description: "Un instante cotidiano capturado en blanco y negro, grano fino y alto contraste.",
    location: "Le Marais, París",
    capturedAt: "2018-10-14",
    category: "blanco-y-negro",
    country: "francia",
    width: 4,
    height: 5,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "costa-amalfitana",
    title: "Costa Amalfitana",
    description: "Casas de colores suspendidas sobre el Tirreno al atardecer.",
    location: "Positano",
    capturedAt: "2020-06-18",
    category: "paisaje",
    country: "italia",
    width: 3,
    height: 4,
    featured: true,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "columnas-romanas",
    title: "Columnas romanas",
    description: "Estudio de luz y geometría entre las ruinas del Foro Romano.",
    location: "Roma",
    capturedAt: "2020-06-10",
    category: "arquitectura",
    country: "italia",
    width: 4,
    height: 5,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "gondolero-venecia-bn",
    title: "Gondolero, Venecia",
    description: "Retrato ambiental en blanco y negro sobre el Gran Canal.",
    location: "Venecia",
    capturedAt: "2020-06-22",
    category: "blanco-y-negro",
    country: "italia",
    width: 4,
    height: 5,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "azulejos-lisboa",
    title: "Azulejos de Lisboa",
    description: "Textura y color en las fachadas del barrio de Alfama.",
    location: "Alfama, Lisboa",
    capturedAt: "2019-05-09",
    category: "urbano",
    country: "portugal",
    width: 4,
    height: 5,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "pescador-al-atardecer",
    title: "Pescador al atardecer",
    description: "Un retrato robado en el puerto de Nazaré, luz dorada sobre el rostro curtido por el mar.",
    location: "Nazaré",
    capturedAt: "2019-05-12",
    category: "retratos",
    country: "portugal",
    width: 4,
    height: 5,
    featured: true,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "arquitectura-alhambra",
    title: "Arcos de la Alhambra",
    description: "Simetría y luz filtrada en los patios nazaríes de Granada.",
    location: "Granada",
    capturedAt: "2019-03-02",
    category: "arquitectura",
    country: "espana",
    width: 4,
    height: 5,
    featured: true,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "flamenco-en-movimiento",
    title: "Flamenco en movimiento",
    description: "Congelando el gesto en plena Feria de Abril, panning de larga exposición.",
    location: "Sevilla",
    capturedAt: "2019-04-20",
    category: "retratos",
    country: "espana",
    width: 3,
    height: 4,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "costa-brava-acantilados",
    title: "Acantilados de la Costa Brava",
    description: "El Mediterráneo golpeando la roca caliza al amanecer.",
    location: "Cap de Creus",
    capturedAt: "2019-06-01",
    category: "paisaje",
    country: "espana",
    width: 3,
    height: 2,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "templo-en-la-niebla",
    title: "Templo en la niebla",
    description: "Fushimi Inari antes del amanecer, cuando los torii aún están vacíos.",
    location: "Kioto",
    capturedAt: "2023-11-08",
    category: "arquitectura",
    country: "japon",
    width: 4,
    height: 5,
    featured: true,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "monte-fuji-invierno",
    title: "Monte Fuji en invierno",
    description: "Simetría perfecta reflejada en el lago Kawaguchiko.",
    location: "Kawaguchiko",
    capturedAt: "2023-11-15",
    category: "paisaje",
    country: "japon",
    width: 3,
    height: 2,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "neon-shibuya",
    title: "Cruce de Shibuya",
    description: "El caos ordenado de Tokio de noche, luces largas y multitud en movimiento.",
    location: "Tokio",
    capturedAt: "2023-11-10",
    category: "urbano",
    country: "japon",
    width: 3,
    height: 4,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "machu-picchu-amanecer",
    title: "Machu Picchu al amanecer",
    description: "Las primeras luces sobre la ciudadela inca, antes de la llegada de los grupos.",
    location: "Machu Picchu",
    capturedAt: "2021-06-03",
    category: "paisaje",
    country: "peru",
    width: 3,
    height: 2,
    featured: true,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "tejedora-andina",
    title: "Tejedora andina",
    description: "Retrato en el mercado de Chinchero, colores vivos y altura de los Andes.",
    location: "Chinchero",
    capturedAt: "2021-06-08",
    category: "retratos",
    country: "peru",
    width: 4,
    height: 5,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "llama-en-altura-bn",
    title: "Llama en altura",
    description: "Fauna andina en blanco y negro, textura de lana contra el cielo plano.",
    location: "Valle Sagrado",
    capturedAt: "2021-06-06",
    category: "naturaleza",
    country: "peru",
    width: 4,
    height: 5,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "color-en-oaxaca",
    title: "Color en Oaxaca",
    description: "Fachadas y textiles conviviendo en una misma calle.",
    location: "Oaxaca",
    capturedAt: "2023-02-20",
    category: "urbano",
    country: "mexico",
    width: 4,
    height: 5,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "desierto-de-sonora",
    title: "Desierto de Sonora",
    description: "Saguaros gigantes recortados contra un cielo de fuego al atardecer.",
    location: "Sonora",
    capturedAt: "2023-02-25",
    category: "paisaje",
    country: "mexico",
    width: 3,
    height: 2,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "skyline-manhattan-bn",
    title: "Skyline de Manhattan",
    description: "Vertical y escala humana, larga exposición desde Brooklyn.",
    location: "Nueva York",
    capturedAt: "2024-01-18",
    category: "blanco-y-negro",
    country: "estados-unidos",
    width: 3,
    height: 2,
    featured: true,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "valle-monumentos",
    title: "Valle de los Monumentos",
    description: "Formaciones rocosas al atardecer en la frontera de Utah y Arizona.",
    location: "Monument Valley",
    capturedAt: "2024-01-25",
    category: "paisaje",
    country: "estados-unidos",
    width: 3,
    height: 2,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "santorini-azul",
    title: "Santorini azul",
    description: "Cúpulas y escaleras blancas contra el Egeo en Oía.",
    location: "Oía, Santorini",
    capturedAt: "2024-06-14",
    category: "urbano",
    country: "grecia",
    width: 4,
    height: 5,
    featured: true,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
  {
    slug: "pescador-griego-bn",
    title: "Pescador griego",
    description: "Retrato ambiental en blanco y negro en el puerto de Naxos.",
    location: "Naxos",
    capturedAt: "2024-06-18",
    category: "blanco-y-negro",
    country: "grecia",
    width: 4,
    height: 5,
    featured: false,
    prices: [DIGITAL_PRICE, ...PRINT_PRICES],
  },
];
